(function () {
  window.SITE_PAGE_I18N = {
    en: {
      page_title: 'Privacy Policy - Eggbeater Water Polo',
      page_description: 'Privacy Policy for Eggbeater Water Polo.',
      lang_label: 'Language',
      doc_title: 'Privacy Policy',
      header_dates: 'Effective date: March 22, 2026 &nbsp;&middot;&nbsp; Last updated: April 4, 2026',
      back_link: '&larr; Back to App',
      intro_html: '<p>Eggbeater is a tournament tracking tool for water polo teams and clubs. It does not sell or share personal data.</p><p>This Privacy Policy describes how the <strong>Eggbeater Water Polo</strong> app ("the App") handles information when you use it at <a href="https://eggbeater.app">eggbeater.app</a> or via our native mobile applications for iOS and Android. By using the App you agree to this policy.</p>',
      sec1_html: '<h2><span class="num">1</span> Information We Collect</h2><p><strong>Information you provide:</strong></p><ul><li>Player roster entries, game scores, live-scoring statistics, and GroupMe Bot IDs you enter are stored only on your device unless explicitly synchronized through supported services.</li></ul><p><strong>Information from Google (if you sign in with Google):</strong></p><ul><li>Your Google account display name, email address, and profile photo are used only to identify your session and show your first name in the App header.</li><li>A Firebase Authentication UID is used to associate your saved preferences with your account in Firestore.</li><li>A Google OAuth access token for Google Calendar is requested at sign-in time and is held in memory only.</li></ul><p><strong>Admin authentication:</strong></p><ul><li>Admins sign in with Google via Firebase Authentication, and a Firebase ID token is sent with each API request for verification.</li><li>Your Firebase UID is stored in a club-specific authorization list to determine admin access.</li><li>Admin ID tokens are refreshed automatically and are never stored persistently on the server.</li></ul>',
      sec2_html: '<h2><span class="num">2</span> How We Use Information</h2><ul><li><strong>Google Calendar access</strong> is used only to create, update, and delete game events in the calendar you choose.</li><li><strong>Push subscription endpoints</strong> are used only to send schedule, reminder, and announcement notifications.</li><li><strong>Google Sign-In</strong> is used only to authenticate your identity and enable cross-device preference sync.</li><li><strong>Firestore preferences</strong> store My Players and selected age groups so your settings can be restored.</li><li><strong>On-device data</strong> such as roster, scores, and stats stays on your device unless explicitly relayed for live features.</li><li><strong>Live score data</strong> may be relayed temporarily so other spectators can receive real-time updates.</li></ul>',
      sec3_html: '<h2><span class="num">3</span> Google API Scopes &amp; Firebase Authentication</h2><p><strong>Firebase Authentication (Google Sign-In):</strong> The App uses Firebase Authentication with Google as the identity provider and requests OpenID scopes for authentication, along with Google Calendar access in the same consent screen.</p><p><strong>Google Calendar scope:</strong> The App requests <code>https://www.googleapis.com/auth/calendar</code> so it can create and manage game events in the calendar you choose.</p><p>On later visits, if calendar sync is connected, the App silently refreshes the access token in the background. Google Calendar tokens are held in memory only and are never written to a server or database.</p><p><strong>Admin panel JWT verification:</strong> Firebase ID tokens are sent as Bearer tokens and verified using Google\'s public signing keys. Tokens are verified and discarded on each request.</p>',
      sec4_html: '<h2><span class="num">4</span> Data Sharing</h2><p>We do not sell, trade, or share your personal information with third parties. The App does rely on third-party infrastructure to operate, including:</p><ul><li><strong>Vercel</strong> for hosting static files.</li><li><strong>Cloudflare Workers / KV</strong> for push delivery, temporary live score relay, and club-scoped tournament data.</li><li><strong>Google Firebase</strong> for authentication and Firestore storage when you sign in.</li><li><strong>Google LLC</strong> for OAuth and Calendar API services.</li><li><strong>Apple</strong> and <strong>Google</strong> for native push delivery and app-store billing.</li><li><strong>RevenueCat</strong> for subscription entitlement management.</li><li><strong>Stripe</strong> for web-based payment processing.</li></ul>',
      sec5_html: '<h2><span class="num">5</span> Data Retention &amp; Deletion</h2><ul><li><strong>On-device data</strong> can be cleared at any time by clearing site data or localStorage on your device.</li><li><strong>Firestore preferences</strong> are retained until you request deletion.</li><li><strong>Firebase Authentication sessions</strong> can be revoked by signing out in the App or through your Google Account permissions page.</li><li><strong>Push subscriptions</strong> are removed when you unsubscribe or expire automatically after inactivity.</li><li><strong>Live score relay data</strong> expires automatically after a short retention period.</li><li><strong>Google Calendar events</strong> created by the App can be deleted by disconnecting calendar sync or deleting them in Google Calendar.</li><li><strong>Admin authorization data</strong> remains until removed by a club admin.</li><li><strong>Tournament archives</strong> remain under the club\'s document path until deleted by a club admin.</li></ul>',
      sec6_html: '<h2><span class="num">6</span> Children\'s Privacy</h2><p>The App is intended for use by parents, guardians, and coaches of team members. While the App may track player first and last names, that data is entered by parents or coaches, stored only on their own device unless explicitly synchronized, and is not knowingly collected directly from children.</p>',
      sec7_html: '<h2><span class="num">7</span> Security</h2><p>All communication between your device and our infrastructure is encrypted via HTTPS/TLS. Google OAuth tokens are never stored in cookies, databases, or persistent server-side storage. On-device data in localStorage is protected by the browser\'s same-origin policy.</p><p>Admin API requests are authenticated using Firebase ID tokens verified against Google\'s public signing keys. Club data remains isolated by club-specific key prefixes and Firestore document paths.</p>',
      sec8_html: '<h2><span class="num">8</span> Changes to This Policy</h2><p>If we make material changes to this Privacy Policy, the Last updated date at the top of this page will be revised. Continued use of the App after changes constitutes acceptance of the updated policy.</p>',
      sec9_html: '<h2><span class="num">9</span> Contact</h2><p>Questions about this Privacy Policy or requests regarding your data can be directed to the administrator of your team\'s Eggbeater deployment.</p>',
      footer_links: '<a href="/">&larr; Back to App</a><a href="/terms.html">Terms of Service</a><a href="/eggbeater-quickstart.pdf" target="_blank">Quick Start Guide &rarr;</a>',
      footer_copy: 'Eggbeater Water Polo &nbsp;&middot;&nbsp; Private tournament tracking for water polo families'
    },
    es: {
      page_title: 'Politica de privacidad - Eggbeater Water Polo',
      page_description: 'Politica de privacidad de Eggbeater Water Polo.',
      lang_label: 'Idioma',
      doc_title: 'Politica de privacidad',
      header_dates: 'Fecha de entrada en vigor: 22 de marzo de 2026 &nbsp;&middot;&nbsp; Ultima actualizacion: 4 de abril de 2026',
      back_link: '&larr; Volver a la app',
      intro_html: '<p>Eggbeater es una herramienta de seguimiento de torneos para equipos y clubes de waterpolo. No vende ni comparte datos personales.</p><p>Esta Politica de Privacidad describe como la app <strong>Eggbeater Water Polo</strong> ("la App") gestiona la informacion cuando la usas en <a href="https://eggbeater.app">eggbeater.app</a> o mediante nuestras apps nativas para iOS y Android. Al usar la App aceptas esta politica.</p>',
      sec1_html: '<h2><span class="num">1</span> Informacion que recopilamos</h2><p><strong>Informacion que proporcionas:</strong></p><ul><li>Las entradas de roster, scores, estadisticas de live scoring y GroupMe Bot IDs se almacenan solo en tu dispositivo salvo que se sincronicen mediante servicios compatibles.</li></ul><p><strong>Informacion de Google:</strong></p><ul><li>El nombre visible, correo y foto de tu cuenta Google se usan solo para identificar tu sesion y mostrar tu nombre en la App.</li><li>Un UID de Firebase Authentication se usa para asociar tus preferencias guardadas en Firestore.</li><li>Un token OAuth de Google Calendar se solicita al iniciar sesion y se mantiene solo en memoria.</li></ul><p><strong>Autenticacion admin:</strong></p><ul><li>Los admins inician sesion con Google via Firebase Authentication y envian un Firebase ID token en cada solicitud API para verificacion.</li><li>Tu Firebase UID se guarda en una lista de autorizacion especifica del club.</li><li>Los tokens admin se renuevan automaticamente y no se almacenan de forma persistente en el servidor.</li></ul>',
      sec2_html: '<h2><span class="num">2</span> Como usamos la informacion</h2><ul><li><strong>El acceso a Google Calendar</strong> se usa solo para crear, actualizar y eliminar eventos de partido en el calendario elegido.</li><li><strong>Los endpoints push</strong> se usan solo para enviar notificaciones de calendario, recordatorios y anuncios.</li><li><strong>Google Sign-In</strong> se usa solo para autenticar tu identidad y sincronizar preferencias entre dispositivos.</li><li><strong>Las preferencias en Firestore</strong> almacenan My Players y grupos de edad seleccionados para restaurar tus ajustes.</li><li><strong>Los datos en dispositivo</strong> como roster, scores y stats se quedan en tu dispositivo salvo que se retransmitan para funciones live.</li><li><strong>Los datos de live score</strong> pueden retransmitirse temporalmente para que otros espectadores reciban actualizaciones en tiempo real.</li></ul>',
      sec3_html: '<h2><span class="num">3</span> Alcances de Google API y Firebase Authentication</h2><p><strong>Firebase Authentication:</strong> La App usa Firebase Authentication con Google como proveedor de identidad y solicita scopes OpenID para autenticacion, junto con acceso a Google Calendar en la misma pantalla de consentimiento.</p><p><strong>Alcance de Google Calendar:</strong> La App solicita <code>https://www.googleapis.com/auth/calendar</code> para crear y gestionar eventos de partido en el calendario elegido.</p><p>En visitas posteriores, si hay calendario conectado, la App refresca el token en segundo plano. Los tokens de Google Calendar se mantienen solo en memoria y nunca se escriben en servidor o base de datos.</p><p><strong>Verificacion JWT del panel admin:</strong> Los Firebase ID tokens se envian como Bearer tokens y se verifican con las claves publicas de Google. Se verifican y descartan en cada solicitud.</p>',
      sec4_html: '<h2><span class="num">4</span> Comparticion de datos</h2><p>No vendemos, intercambiamos ni compartimos tu informacion personal con terceros. La App si depende de infraestructura de terceros para funcionar, incluyendo:</p><ul><li><strong>Vercel</strong> para alojar archivos estaticos.</li><li><strong>Cloudflare Workers / KV</strong> para entrega push, retransmision temporal de live score y datos de torneo por club.</li><li><strong>Google Firebase</strong> para autenticacion y almacenamiento en Firestore cuando inicias sesion.</li><li><strong>Google LLC</strong> para OAuth y servicios de Calendar API.</li><li><strong>Apple</strong> y <strong>Google</strong> para entrega de push nativo y cobro en las tiendas.</li><li><strong>RevenueCat</strong> para gestion de entitlements de suscripcion.</li><li><strong>Stripe</strong> para procesamiento de pagos web.</li></ul>',
      sec5_html: '<h2><span class="num">5</span> Retencion y eliminacion de datos</h2><ul><li><strong>Los datos en dispositivo</strong> pueden borrarse limpiando el site data o localStorage de tu dispositivo.</li><li><strong>Las preferencias en Firestore</strong> se conservan hasta que solicites su eliminacion.</li><li><strong>Las sesiones de Firebase Authentication</strong> pueden revocarse cerrando sesion en la App o desde la pagina de permisos de tu cuenta Google.</li><li><strong>Las suscripciones push</strong> se eliminan al darte de baja o caducan automaticamente tras inactividad.</li><li><strong>Los datos de live score</strong> expiran automaticamente tras un periodo corto.</li><li><strong>Los eventos de Google Calendar</strong> creados por la App pueden borrarse desconectando la sincronizacion o eliminandolos manualmente.</li><li><strong>Los datos de autorizacion admin</strong> permanecen hasta que un admin del club los elimine.</li><li><strong>Los archivos de torneo</strong> permanecen bajo la ruta del club hasta que un admin los elimine.</li></ul>',
      sec6_html: '<h2><span class="num">6</span> Privacidad infantil</h2><p>La App esta pensada para padres, tutores y coaches de miembros del equipo. Aunque la App pueda manejar nombres de jugadores, esos datos los introducen padres o coaches, se almacenan solo en su dispositivo salvo sincronizacion explicita y no se recopilan directamente de menores de forma consciente.</p>',
      sec7_html: '<h2><span class="num">7</span> Seguridad</h2><p>Toda comunicacion entre tu dispositivo y nuestra infraestructura esta cifrada mediante HTTPS/TLS. Los tokens OAuth de Google nunca se almacenan en cookies, bases de datos ni almacenamiento persistente del servidor. Los datos locales quedan protegidos por la politica same-origin del navegador.</p><p>Las solicitudes API del admin se autentican con Firebase ID tokens verificados frente a las claves publicas de Google. Los datos de cada club permanecen aislados por prefijos de clave y rutas de documentos especificas del club.</p>',
      sec8_html: '<h2><span class="num">8</span> Cambios en esta politica</h2><p>Si realizamos cambios materiales en esta Politica de Privacidad, revisaremos la fecha de ultima actualizacion en la parte superior. El uso continuado de la App tras esos cambios implica aceptacion de la politica actualizada.</p>',
      sec9_html: '<h2><span class="num">9</span> Contacto</h2><p>Las preguntas sobre esta Politica de Privacidad o las solicitudes relacionadas con tus datos pueden dirigirse al administrador del despliegue de Eggbeater de tu equipo.</p>',
      footer_links: '<a href="/">&larr; Volver a la app</a><a href="/terms.html">Terminos del servicio</a><a href="/eggbeater-quickstart.pdf" target="_blank">Guia rapida &rarr;</a>',
      footer_copy: 'Eggbeater Water Polo &nbsp;&middot;&nbsp; Seguimiento privado de torneos para familias de waterpolo'
    },
    fr: {
      page_title: 'Politique de confidentialite - Eggbeater Water Polo',
      page_description: 'Politique de confidentialite de Eggbeater Water Polo.',
      lang_label: 'Langue',
      doc_title: 'Politique de confidentialite',
      header_dates: 'Date d effet : 22 mars 2026 &nbsp;&middot;&nbsp; Derniere mise a jour : 4 avril 2026',
      back_link: '&larr; Retour a l app',
      intro_html: '<p>Eggbeater est un outil de suivi de tournoi pour les equipes et clubs de water-polo. Il ne vend ni ne partage de donnees personnelles.</p><p>Cette Politique de confidentialite decrit la facon dont l app <strong>Eggbeater Water Polo</strong> ("l App") traite les informations lorsque vous l utilisez sur <a href="https://eggbeater.app">eggbeater.app</a> ou via nos applications natives iOS et Android. En utilisant l App, vous acceptez cette politique.</p>',
      sec1_html: '<h2><span class="num">1</span> Informations que nous collectons</h2><p><strong>Informations que vous fournissez :</strong></p><ul><li>Les donnees de roster, scores, statistiques de live scoring et GroupMe Bot IDs sont stockees uniquement sur votre appareil sauf synchronisation explicite via des services compatibles.</li></ul><p><strong>Informations provenant de Google :</strong></p><ul><li>Le nom affiche, l e-mail et la photo de votre compte Google sont utilises uniquement pour identifier votre session et afficher votre prenom dans l App.</li><li>Un UID Firebase Authentication est utilise pour associer vos preferences sauvegardees dans Firestore.</li><li>Un jeton OAuth Google Calendar est demande a la connexion et conserve uniquement en memoire.</li></ul><p><strong>Authentification admin :</strong></p><ul><li>Les admins se connectent avec Google via Firebase Authentication et envoient un Firebase ID token avec chaque requete API pour verification.</li><li>Votre Firebase UID est stocke dans une liste d autorisation propre au club.</li><li>Les jetons admin sont renouveles automatiquement et ne sont jamais stockes durablement sur le serveur.</li></ul>',
      sec2_html: '<h2><span class="num">2</span> Comment nous utilisons les informations</h2><ul><li><strong>L acces a Google Calendar</strong> est utilise uniquement pour creer, mettre a jour et supprimer les evenements de match dans le calendrier choisi.</li><li><strong>Les endpoints push</strong> servent uniquement a envoyer des notifications de calendrier, des rappels et des annonces.</li><li><strong>Google Sign-In</strong> sert uniquement a authentifier votre identite et a synchroniser les preferences entre appareils.</li><li><strong>Les preferences Firestore</strong> stockent My Players et les categories selectionnees afin de restaurer vos reglages.</li><li><strong>Les donnees locales</strong> comme le roster, les scores et les stats restent sur votre appareil sauf relais explicite pour des fonctions live.</li><li><strong>Les donnees de live score</strong> peuvent etre relayees temporairement pour permettre aux autres spectateurs de recevoir des mises a jour en temps reel.</li></ul>',
      sec3_html: '<h2><span class="num">3</span> Portee Google API et Firebase Authentication</h2><p><strong>Firebase Authentication :</strong> L App utilise Firebase Authentication avec Google comme fournisseur d identite et demande les scopes OpenID pour l authentification, ainsi que l acces a Google Calendar dans le meme ecran de consentement.</p><p><strong>Portee Google Calendar :</strong> L App demande <code>https://www.googleapis.com/auth/calendar</code> afin de creer et gerer les evenements de match dans le calendrier choisi.</p><p>Lors des visites suivantes, si un calendrier est connecte, l App rafraichit le jeton en arriere-plan. Les jetons Google Calendar sont conserves uniquement en memoire et ne sont jamais ecrits sur un serveur ou une base de donnees.</p><p><strong>Verification JWT du panneau admin :</strong> Les Firebase ID tokens sont envoyes comme Bearer tokens et verifies avec les cles publiques de Google. Ils sont verifies puis rejetes a chaque requete.</p>',
      sec4_html: '<h2><span class="num">4</span> Partage des donnees</h2><p>Nous ne vendons, n echangeons ni ne partageons vos informations personnelles avec des tiers. L App s appuie toutefois sur une infrastructure tierce, notamment :</p><ul><li><strong>Vercel</strong> pour l hebergement des fichiers statiques.</li><li><strong>Cloudflare Workers / KV</strong> pour la livraison push, le relais temporaire des live scores et les donnees de tournoi par club.</li><li><strong>Google Firebase</strong> pour l authentification et le stockage Firestore lorsque vous vous connectez.</li><li><strong>Google LLC</strong> pour OAuth et les services Calendar API.</li><li><strong>Apple</strong> et <strong>Google</strong> pour la livraison push native et la facturation en boutique.</li><li><strong>RevenueCat</strong> pour la gestion des entitlements d abonnement.</li><li><strong>Stripe</strong> pour le traitement des paiements web.</li></ul>',
      sec5_html: '<h2><span class="num">5</span> Retention et suppression des donnees</h2><ul><li><strong>Les donnees locales</strong> peuvent etre effacees en supprimant les donnees de site ou le localStorage de votre appareil.</li><li><strong>Les preferences Firestore</strong> sont conservees jusqu a demande de suppression.</li><li><strong>Les sessions Firebase Authentication</strong> peuvent etre revoquees en se deconnectant dans l App ou depuis la page des autorisations Google.</li><li><strong>Les abonnements push</strong> sont supprimes lors du desabonnement ou expirent automatiquement apres inactivite.</li><li><strong>Les donnees de live score</strong> expirent automatiquement apres une courte duree.</li><li><strong>Les evenements Google Calendar</strong> crees par l App peuvent etre supprimes en deconnectant la synchronisation ou manuellement.</li><li><strong>Les donnees d autorisation admin</strong> restent jusqu a suppression par un admin du club.</li><li><strong>Les archives de tournoi</strong> restent sous le chemin du club jusqu a suppression par un admin.</li></ul>',
      sec6_html: '<h2><span class="num">6</span> Vie privee des enfants</h2><p>L App est destinee aux parents, tuteurs et coaches des membres de l equipe. Bien que l App puisse manipuler des noms de joueurs, ces donnees sont saisies par des parents ou coaches, stockees seulement sur leur appareil sauf synchronisation explicite, et ne sont pas sciemment collecte?es directement aupres d enfants.</p>',
      sec7_html: '<h2><span class="num">7</span> Securite</h2><p>Toutes les communications entre votre appareil et notre infrastructure sont chiffre?es via HTTPS/TLS. Les jetons OAuth Google ne sont jamais stockes dans des cookies, bases de donnees ou stockages persistants cote serveur. Les donnees locales sont protegees par la politique same-origin du navigateur.</p><p>Les requetes API admin sont authentifiees avec des Firebase ID tokens verifies a l aide des cles publiques de Google. Les donnees de chaque club restent isolees par des prefixes de cle et des chemins de documents specifiques au club.</p>',
      sec8_html: '<h2><span class="num">8</span> Modifications de cette politique</h2><p>Si nous apportons des modifications importantes a cette Politique de confidentialite, la date de derniere mise a jour en haut de page sera revisee. La poursuite de l utilisation de l App apres ces changements vaut acceptation de la politique mise a jour.</p>',
      sec9_html: '<h2><span class="num">9</span> Contact</h2><p>Les questions au sujet de cette Politique de confidentialite ou les demandes relatives a vos donnees peuvent etre adressees a l administrateur du deploiement Eggbeater de votre equipe.</p>',
      footer_links: '<a href="/">&larr; Retour a l app</a><a href="/terms.html">Conditions d utilisation</a><a href="/eggbeater-quickstart.pdf" target="_blank">Guide rapide &rarr;</a>',
      footer_copy: 'Eggbeater Water Polo &nbsp;&middot;&nbsp; Suivi prive des tournois pour les familles de water-polo'
    }
  };

  window.SITE_I18N_BINDINGS = [
    { selector: '.intro-card', key: 'intro_html', attr: 'html' },
    { selector: 'main section:nth-of-type(1)', key: 'sec1_html', attr: 'html' },
    { selector: 'main section:nth-of-type(2)', key: 'sec2_html', attr: 'html' },
    { selector: 'main section:nth-of-type(3)', key: 'sec3_html', attr: 'html' },
    { selector: 'main section:nth-of-type(4)', key: 'sec4_html', attr: 'html' },
    { selector: 'main section:nth-of-type(5)', key: 'sec5_html', attr: 'html' },
    { selector: 'main section:nth-of-type(6)', key: 'sec6_html', attr: 'html' },
    { selector: 'main section:nth-of-type(7)', key: 'sec7_html', attr: 'html' },
    { selector: 'main section:nth-of-type(8)', key: 'sec8_html', attr: 'html' },
    { selector: 'main section:nth-of-type(9)', key: 'sec9_html', attr: 'html' },
    { selector: '.footer-links', key: 'footer_links', attr: 'html' },
    { selector: '.footer-copy', key: 'footer_copy', attr: 'html' }
  ];
})();

